@startuml
:user: --> (Use case 1)
:user: -> (Use case 2)

(Use case 3) <.. :user2:
(Use case 4) <- :user2:

:user3: -left-> (dummyLeft)
:user3: -right-> (dummyRight)
:user3: -up-> (dummyUp)
:user3: -down-> (dummyDown)
@enduml